substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Step 1: Generate from Protobuf
  # - name: bufbuild/buf@sha256:d104e96432a276ee21eaa2c905c22c81c6ebb3a5ffb0750332f91930a426858e
  #   args:
  #     - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel@sha256:5a00ecb9f2a1351077765758077edbc849140db52c09fdbdfbe54d72c424e413
    args: [run, //cmd/api-server:container]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:9e9cb922eebbd1bd9a7bd0dbf09ec73b43f1bf8f4d28d463ca84eb882e0ffa81
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:9e9cb922eebbd1bd9a7bd0dbf09ec73b43f1bf8f4d28d463ca84eb882e0ffa81
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:9e9cb922eebbd1bd9a7bd0dbf09ec73b43f1bf8f4d28d463ca84eb882e0ffa81
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:9e9cb922eebbd1bd9a7bd0dbf09ec73b43f1bf8f4d28d463ca84eb882e0ffa81
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:d392b36bdeda6a4008d611342535ee866595c412e6252ccfe605be330ba76bd0
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
