substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:6552d40d47e38a9c976ff6541d71e1d26f6cdee6be161a311c00a2a597370e50
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Tag image with commit sha
  - name: gcr.io/cloud-builders/docker@sha256:e8f8f5493b00cf31e510b9ead4761102da89b2261dfad4eb9e35f24f3a2017be
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker@sha256:e8f8f5493b00cf31e510b9ead4761102da89b2261dfad4eb9e35f24f3a2017be
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Push image
  - name: gcr.io/cloud-builders/docker@sha256:e8f8f5493b00cf31e510b9ead4761102da89b2261dfad4eb9e35f24f3a2017be
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Deploy new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:6291b7521d4b49075c045076e316e4c17a7d85489d76e25bc32417480b0b4eca
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,PAYMENT_SERVICE_HOST=$_PAYMENT_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
