substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:f9e87f11e5f4de47a94e3276f02aeb273d17441b10285d721fc147d3b8823015
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Tag image with commit sha
  - name: gcr.io/cloud-builders/docker@sha256:50d0ac08fe07dbe12038c8244737cfcc025e80060b82dac85b0d1471150aa322
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker@sha256:50d0ac08fe07dbe12038c8244737cfcc025e80060b82dac85b0d1471150aa322
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Push image
  - name: gcr.io/cloud-builders/docker@sha256:50d0ac08fe07dbe12038c8244737cfcc025e80060b82dac85b0d1471150aa322
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Deploy new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:1622e46c7fb563d8c2bb9f62b6bb7ab2c613b1c583d86f6aab237a1f783b919c
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,PAYMENT_SERVICE_HOST=$_PAYMENT_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
