substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:bb598a39824e583c01e609ea20a00e0af39ece2225ebd28890d2c094e9da1df0
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Tag image with commit sha
  - name: gcr.io/cloud-builders/docker@sha256:b2e64911ae2a214d80f839319dffd0afb8964881381146e08512edd5b5181277
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker@sha256:b2e64911ae2a214d80f839319dffd0afb8964881381146e08512edd5b5181277
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Push image
  - name: gcr.io/cloud-builders/docker@sha256:b2e64911ae2a214d80f839319dffd0afb8964881381146e08512edd5b5181277
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Deploy new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:01e38cd50099ff39643f56cb625d902a668d97790a872f3f294996e935899edd
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,PAYMENT_SERVICE_HOST=$_PAYMENT_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
