substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:f87d6c0cf0e297841b2c734eec46eb6c09a345e879be68179d42d12f0b3f89ee
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Tag image with commit sha
  - name: gcr.io/cloud-builders/docker@sha256:b46cb3b8fecedaa52c134d5d5a02e858bd546372926bba5a2d71d8c905071098
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker@sha256:b46cb3b8fecedaa52c134d5d5a02e858bd546372926bba5a2d71d8c905071098
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Push image
  - name: gcr.io/cloud-builders/docker@sha256:b46cb3b8fecedaa52c134d5d5a02e858bd546372926bba5a2d71d8c905071098
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Deploy new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:e2f82c4451cf3ba5d4606759b1f14ad3597b2709cd8201bf6f9e0f7e4e5982eb
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,PAYMENT_SERVICE_HOST=$_PAYMENT_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
