substitutions:
  _SERVICE_NAME: marketplace-service

steps:
  # Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel:7.0.1@sha256:3d51a4ae84f716db39bdd897ce0b645301a94c5f97e77b26bd407405d866d027
    id: build
    args:
      [
        run,
        //cmd/api-server:container,
        --remote_cache=https://storage.googleapis.com/$_BAZEL_REMOTE_CACHE_BUCKET,
        --google_default_credentials,
      ]

  # Tag image with commit sha
  - name: gcr.io/cloud-builders/docker@sha256:d077f1f731f094e193338015eeae4af7669b2bae938bd020e714cebeb78ad65f
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker@sha256:d077f1f731f094e193338015eeae4af7669b2bae938bd020e714cebeb78ad65f
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Push image
  - name: gcr.io/cloud-builders/docker@sha256:d077f1f731f094e193338015eeae4af7669b2bae938bd020e714cebeb78ad65f
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Deploy new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:a51abe90cb1baa951d553baf0b1923ecddbe95de8ed32e69c49f7ed733acfd0a
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,PAYMENT_SERVICE_HOST=$_PAYMENT_SERVICE_HOST,DRIVER_SERVICE_HOST=$_DRIVER_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
