// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ride-app/marketplace-service/internal/repositories/status (interfaces: StatusRepository)
//
// Generated by this command:
//
//	mockgen -destination ./mock/status_repository.go . StatusRepository
//

// Package mock_status is a generated GoMock package.
package mock_status

import (
	context "context"
	reflect "reflect"

	driverv1alpha1 "buf.build/gen/go/ride/driver/protocolbuffers/go/ride/driver/v1alpha1"
	logger "github.com/dragonfish-tech/go/pkg/logger"
	v1alpha1 "github.com/ride-app/marketplace-service/api/ride/marketplace/v1alpha1"
	statusrepository "github.com/ride-app/marketplace-service/internal/repositories/status"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusRepository is a mock of StatusRepository interface.
type MockStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatusRepositoryMockRecorder
}

// MockStatusRepositoryMockRecorder is the mock recorder for MockStatusRepository.
type MockStatusRepositoryMockRecorder struct {
	mock *MockStatusRepository
}

// NewMockStatusRepository creates a new mock instance.
func NewMockStatusRepository(ctrl *gomock.Controller) *MockStatusRepository {
	mock := &MockStatusRepository{ctrl: ctrl}
	mock.recorder = &MockStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusRepository) EXPECT() *MockStatusRepositoryMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockStatusRepository) GetStatus(arg0 context.Context, arg1 logger.Logger, arg2 string) (*v1alpha1.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockStatusRepositoryMockRecorder) GetStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStatusRepository)(nil).GetStatus), arg0, arg1, arg2)
}

// GoOffline mocks base method.
func (m *MockStatusRepository) GoOffline(arg0 context.Context, arg1 logger.Logger, arg2 string) (*v1alpha1.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoOffline", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoOffline indicates an expected call of GoOffline.
func (mr *MockStatusRepositoryMockRecorder) GoOffline(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoOffline", reflect.TypeOf((*MockStatusRepository)(nil).GoOffline), arg0, arg1, arg2)
}

// GoOnline mocks base method.
func (m *MockStatusRepository) GoOnline(arg0 context.Context, arg1 logger.Logger, arg2 string, arg3 *driverv1alpha1.Vehicle) (*v1alpha1.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoOnline", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v1alpha1.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoOnline indicates an expected call of GoOnline.
func (mr *MockStatusRepositoryMockRecorder) GoOnline(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoOnline", reflect.TypeOf((*MockStatusRepository)(nil).GoOnline), arg0, arg1, arg2, arg3)
}

// ListenStatus mocks base method.
func (m *MockStatusRepository) ListenStatus(arg0 context.Context, arg1 logger.Logger, arg2 string, arg3 chan<- *statusrepository.StatusStreamResponse) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenStatus", arg0, arg1, arg2, arg3)
}

// ListenStatus indicates an expected call of ListenStatus.
func (mr *MockStatusRepositoryMockRecorder) ListenStatus(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenStatus", reflect.TypeOf((*MockStatusRepository)(nil).ListenStatus), arg0, arg1, arg2, arg3)
}
