// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ride/marketplace/v1alpha1/service.proto

package marketplacev1alpha1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1alpha1 "github.com/ride-app/marketplace-service/api/ride/marketplace/v1alpha1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MarketplaceServiceName is the fully-qualified name of the MarketplaceService service.
	MarketplaceServiceName = "ride.marketplace.v1alpha1.MarketplaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MarketplaceServiceGoOnlineProcedure is the fully-qualified name of the MarketplaceService's
	// GoOnline RPC.
	MarketplaceServiceGoOnlineProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/GoOnline"
	// MarketplaceServiceGoOfflineProcedure is the fully-qualified name of the MarketplaceService's
	// GoOffline RPC.
	MarketplaceServiceGoOfflineProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/GoOffline"
	// MarketplaceServiceGetStatusProcedure is the fully-qualified name of the MarketplaceService's
	// GetStatus RPC.
	MarketplaceServiceGetStatusProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/GetStatus"
	// MarketplaceServiceWatchStatusProcedure is the fully-qualified name of the MarketplaceService's
	// WatchStatus RPC.
	MarketplaceServiceWatchStatusProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/WatchStatus"
	// MarketplaceServiceGetLocationProcedure is the fully-qualified name of the MarketplaceService's
	// GetLocation RPC.
	MarketplaceServiceGetLocationProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/GetLocation"
	// MarketplaceServiceWatchLocationProcedure is the fully-qualified name of the MarketplaceService's
	// WatchLocation RPC.
	MarketplaceServiceWatchLocationProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/WatchLocation"
	// MarketplaceServiceUpdateLocationProcedure is the fully-qualified name of the MarketplaceService's
	// UpdateLocation RPC.
	MarketplaceServiceUpdateLocationProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/UpdateLocation"
	// MarketplaceServiceCreateTripProcedure is the fully-qualified name of the MarketplaceService's
	// CreateTrip RPC.
	MarketplaceServiceCreateTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/CreateTrip"
	// MarketplaceServiceGetTripProcedure is the fully-qualified name of the MarketplaceService's
	// GetTrip RPC.
	MarketplaceServiceGetTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/GetTrip"
	// MarketplaceServiceWatchTripProcedure is the fully-qualified name of the MarketplaceService's
	// WatchTrip RPC.
	MarketplaceServiceWatchTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/WatchTrip"
	// MarketplaceServiceVerifyTripProcedure is the fully-qualified name of the MarketplaceService's
	// VerifyTrip RPC.
	MarketplaceServiceVerifyTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/VerifyTrip"
	// MarketplaceServiceStartTripProcedure is the fully-qualified name of the MarketplaceService's
	// StartTrip RPC.
	MarketplaceServiceStartTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/StartTrip"
	// MarketplaceServiceCancelTripProcedure is the fully-qualified name of the MarketplaceService's
	// CancelTrip RPC.
	MarketplaceServiceCancelTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/CancelTrip"
	// MarketplaceServiceEndTripProcedure is the fully-qualified name of the MarketplaceService's
	// EndTrip RPC.
	MarketplaceServiceEndTripProcedure = "/ride.marketplace.v1alpha1.MarketplaceService/EndTrip"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	marketplaceServiceServiceDescriptor              = v1alpha1.File_ride_marketplace_v1alpha1_service_proto.Services().ByName("MarketplaceService")
	marketplaceServiceGoOnlineMethodDescriptor       = marketplaceServiceServiceDescriptor.Methods().ByName("GoOnline")
	marketplaceServiceGoOfflineMethodDescriptor      = marketplaceServiceServiceDescriptor.Methods().ByName("GoOffline")
	marketplaceServiceGetStatusMethodDescriptor      = marketplaceServiceServiceDescriptor.Methods().ByName("GetStatus")
	marketplaceServiceWatchStatusMethodDescriptor    = marketplaceServiceServiceDescriptor.Methods().ByName("WatchStatus")
	marketplaceServiceGetLocationMethodDescriptor    = marketplaceServiceServiceDescriptor.Methods().ByName("GetLocation")
	marketplaceServiceWatchLocationMethodDescriptor  = marketplaceServiceServiceDescriptor.Methods().ByName("WatchLocation")
	marketplaceServiceUpdateLocationMethodDescriptor = marketplaceServiceServiceDescriptor.Methods().ByName("UpdateLocation")
	marketplaceServiceCreateTripMethodDescriptor     = marketplaceServiceServiceDescriptor.Methods().ByName("CreateTrip")
	marketplaceServiceGetTripMethodDescriptor        = marketplaceServiceServiceDescriptor.Methods().ByName("GetTrip")
	marketplaceServiceWatchTripMethodDescriptor      = marketplaceServiceServiceDescriptor.Methods().ByName("WatchTrip")
	marketplaceServiceVerifyTripMethodDescriptor     = marketplaceServiceServiceDescriptor.Methods().ByName("VerifyTrip")
	marketplaceServiceStartTripMethodDescriptor      = marketplaceServiceServiceDescriptor.Methods().ByName("StartTrip")
	marketplaceServiceCancelTripMethodDescriptor     = marketplaceServiceServiceDescriptor.Methods().ByName("CancelTrip")
	marketplaceServiceEndTripMethodDescriptor        = marketplaceServiceServiceDescriptor.Methods().ByName("EndTrip")
)

// MarketplaceServiceClient is a client for the ride.marketplace.v1alpha1.MarketplaceService
// service.
type MarketplaceServiceClient interface {
	GoOnline(context.Context, *connect.Request[v1alpha1.GoOnlineRequest]) (*connect.Response[v1alpha1.GoOnlineResponse], error)
	GoOffline(context.Context, *connect.Request[v1alpha1.GoOfflineRequest]) (*connect.Response[v1alpha1.GoOfflineResponse], error)
	GetStatus(context.Context, *connect.Request[v1alpha1.GetStatusRequest]) (*connect.Response[v1alpha1.GetStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[v1alpha1.WatchStatusRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchStatusResponse], error)
	GetLocation(context.Context, *connect.Request[v1alpha1.GetLocationRequest]) (*connect.Response[v1alpha1.GetLocationResponse], error)
	WatchLocation(context.Context, *connect.Request[v1alpha1.WatchLocationRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchLocationResponse], error)
	UpdateLocation(context.Context, *connect.Request[v1alpha1.UpdateLocationRequest]) (*connect.Response[v1alpha1.UpdateLocationResponse], error)
	CreateTrip(context.Context, *connect.Request[v1alpha1.CreateTripRequest]) (*connect.Response[v1alpha1.CreateTripResponse], error)
	GetTrip(context.Context, *connect.Request[v1alpha1.GetTripRequest]) (*connect.Response[v1alpha1.GetTripResponse], error)
	WatchTrip(context.Context, *connect.Request[v1alpha1.WatchTripRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchTripResponse], error)
	VerifyTrip(context.Context, *connect.Request[v1alpha1.VerifyTripRequest]) (*connect.Response[v1alpha1.VerifyTripResponse], error)
	StartTrip(context.Context, *connect.Request[v1alpha1.StartTripRequest]) (*connect.Response[v1alpha1.StartTripResponse], error)
	CancelTrip(context.Context, *connect.Request[v1alpha1.CancelTripRequest]) (*connect.Response[v1alpha1.CancelTripResponse], error)
	EndTrip(context.Context, *connect.Request[v1alpha1.EndTripRequest]) (*connect.Response[v1alpha1.EndTripResponse], error)
}

// NewMarketplaceServiceClient constructs a client for the
// ride.marketplace.v1alpha1.MarketplaceService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMarketplaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MarketplaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &marketplaceServiceClient{
		goOnline: connect.NewClient[v1alpha1.GoOnlineRequest, v1alpha1.GoOnlineResponse](
			httpClient,
			baseURL+MarketplaceServiceGoOnlineProcedure,
			connect.WithSchema(marketplaceServiceGoOnlineMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		goOffline: connect.NewClient[v1alpha1.GoOfflineRequest, v1alpha1.GoOfflineResponse](
			httpClient,
			baseURL+MarketplaceServiceGoOfflineProcedure,
			connect.WithSchema(marketplaceServiceGoOfflineMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[v1alpha1.GetStatusRequest, v1alpha1.GetStatusResponse](
			httpClient,
			baseURL+MarketplaceServiceGetStatusProcedure,
			connect.WithSchema(marketplaceServiceGetStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		watchStatus: connect.NewClient[v1alpha1.WatchStatusRequest, v1alpha1.WatchStatusResponse](
			httpClient,
			baseURL+MarketplaceServiceWatchStatusProcedure,
			connect.WithSchema(marketplaceServiceWatchStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getLocation: connect.NewClient[v1alpha1.GetLocationRequest, v1alpha1.GetLocationResponse](
			httpClient,
			baseURL+MarketplaceServiceGetLocationProcedure,
			connect.WithSchema(marketplaceServiceGetLocationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		watchLocation: connect.NewClient[v1alpha1.WatchLocationRequest, v1alpha1.WatchLocationResponse](
			httpClient,
			baseURL+MarketplaceServiceWatchLocationProcedure,
			connect.WithSchema(marketplaceServiceWatchLocationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateLocation: connect.NewClient[v1alpha1.UpdateLocationRequest, v1alpha1.UpdateLocationResponse](
			httpClient,
			baseURL+MarketplaceServiceUpdateLocationProcedure,
			connect.WithSchema(marketplaceServiceUpdateLocationMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createTrip: connect.NewClient[v1alpha1.CreateTripRequest, v1alpha1.CreateTripResponse](
			httpClient,
			baseURL+MarketplaceServiceCreateTripProcedure,
			connect.WithSchema(marketplaceServiceCreateTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTrip: connect.NewClient[v1alpha1.GetTripRequest, v1alpha1.GetTripResponse](
			httpClient,
			baseURL+MarketplaceServiceGetTripProcedure,
			connect.WithSchema(marketplaceServiceGetTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		watchTrip: connect.NewClient[v1alpha1.WatchTripRequest, v1alpha1.WatchTripResponse](
			httpClient,
			baseURL+MarketplaceServiceWatchTripProcedure,
			connect.WithSchema(marketplaceServiceWatchTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		verifyTrip: connect.NewClient[v1alpha1.VerifyTripRequest, v1alpha1.VerifyTripResponse](
			httpClient,
			baseURL+MarketplaceServiceVerifyTripProcedure,
			connect.WithSchema(marketplaceServiceVerifyTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		startTrip: connect.NewClient[v1alpha1.StartTripRequest, v1alpha1.StartTripResponse](
			httpClient,
			baseURL+MarketplaceServiceStartTripProcedure,
			connect.WithSchema(marketplaceServiceStartTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelTrip: connect.NewClient[v1alpha1.CancelTripRequest, v1alpha1.CancelTripResponse](
			httpClient,
			baseURL+MarketplaceServiceCancelTripProcedure,
			connect.WithSchema(marketplaceServiceCancelTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		endTrip: connect.NewClient[v1alpha1.EndTripRequest, v1alpha1.EndTripResponse](
			httpClient,
			baseURL+MarketplaceServiceEndTripProcedure,
			connect.WithSchema(marketplaceServiceEndTripMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// marketplaceServiceClient implements MarketplaceServiceClient.
type marketplaceServiceClient struct {
	goOnline       *connect.Client[v1alpha1.GoOnlineRequest, v1alpha1.GoOnlineResponse]
	goOffline      *connect.Client[v1alpha1.GoOfflineRequest, v1alpha1.GoOfflineResponse]
	getStatus      *connect.Client[v1alpha1.GetStatusRequest, v1alpha1.GetStatusResponse]
	watchStatus    *connect.Client[v1alpha1.WatchStatusRequest, v1alpha1.WatchStatusResponse]
	getLocation    *connect.Client[v1alpha1.GetLocationRequest, v1alpha1.GetLocationResponse]
	watchLocation  *connect.Client[v1alpha1.WatchLocationRequest, v1alpha1.WatchLocationResponse]
	updateLocation *connect.Client[v1alpha1.UpdateLocationRequest, v1alpha1.UpdateLocationResponse]
	createTrip     *connect.Client[v1alpha1.CreateTripRequest, v1alpha1.CreateTripResponse]
	getTrip        *connect.Client[v1alpha1.GetTripRequest, v1alpha1.GetTripResponse]
	watchTrip      *connect.Client[v1alpha1.WatchTripRequest, v1alpha1.WatchTripResponse]
	verifyTrip     *connect.Client[v1alpha1.VerifyTripRequest, v1alpha1.VerifyTripResponse]
	startTrip      *connect.Client[v1alpha1.StartTripRequest, v1alpha1.StartTripResponse]
	cancelTrip     *connect.Client[v1alpha1.CancelTripRequest, v1alpha1.CancelTripResponse]
	endTrip        *connect.Client[v1alpha1.EndTripRequest, v1alpha1.EndTripResponse]
}

// GoOnline calls ride.marketplace.v1alpha1.MarketplaceService.GoOnline.
func (c *marketplaceServiceClient) GoOnline(ctx context.Context, req *connect.Request[v1alpha1.GoOnlineRequest]) (*connect.Response[v1alpha1.GoOnlineResponse], error) {
	return c.goOnline.CallUnary(ctx, req)
}

// GoOffline calls ride.marketplace.v1alpha1.MarketplaceService.GoOffline.
func (c *marketplaceServiceClient) GoOffline(ctx context.Context, req *connect.Request[v1alpha1.GoOfflineRequest]) (*connect.Response[v1alpha1.GoOfflineResponse], error) {
	return c.goOffline.CallUnary(ctx, req)
}

// GetStatus calls ride.marketplace.v1alpha1.MarketplaceService.GetStatus.
func (c *marketplaceServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1alpha1.GetStatusRequest]) (*connect.Response[v1alpha1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// WatchStatus calls ride.marketplace.v1alpha1.MarketplaceService.WatchStatus.
func (c *marketplaceServiceClient) WatchStatus(ctx context.Context, req *connect.Request[v1alpha1.WatchStatusRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchStatusResponse], error) {
	return c.watchStatus.CallServerStream(ctx, req)
}

// GetLocation calls ride.marketplace.v1alpha1.MarketplaceService.GetLocation.
func (c *marketplaceServiceClient) GetLocation(ctx context.Context, req *connect.Request[v1alpha1.GetLocationRequest]) (*connect.Response[v1alpha1.GetLocationResponse], error) {
	return c.getLocation.CallUnary(ctx, req)
}

// WatchLocation calls ride.marketplace.v1alpha1.MarketplaceService.WatchLocation.
func (c *marketplaceServiceClient) WatchLocation(ctx context.Context, req *connect.Request[v1alpha1.WatchLocationRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchLocationResponse], error) {
	return c.watchLocation.CallServerStream(ctx, req)
}

// UpdateLocation calls ride.marketplace.v1alpha1.MarketplaceService.UpdateLocation.
func (c *marketplaceServiceClient) UpdateLocation(ctx context.Context, req *connect.Request[v1alpha1.UpdateLocationRequest]) (*connect.Response[v1alpha1.UpdateLocationResponse], error) {
	return c.updateLocation.CallUnary(ctx, req)
}

// CreateTrip calls ride.marketplace.v1alpha1.MarketplaceService.CreateTrip.
func (c *marketplaceServiceClient) CreateTrip(ctx context.Context, req *connect.Request[v1alpha1.CreateTripRequest]) (*connect.Response[v1alpha1.CreateTripResponse], error) {
	return c.createTrip.CallUnary(ctx, req)
}

// GetTrip calls ride.marketplace.v1alpha1.MarketplaceService.GetTrip.
func (c *marketplaceServiceClient) GetTrip(ctx context.Context, req *connect.Request[v1alpha1.GetTripRequest]) (*connect.Response[v1alpha1.GetTripResponse], error) {
	return c.getTrip.CallUnary(ctx, req)
}

// WatchTrip calls ride.marketplace.v1alpha1.MarketplaceService.WatchTrip.
func (c *marketplaceServiceClient) WatchTrip(ctx context.Context, req *connect.Request[v1alpha1.WatchTripRequest]) (*connect.ServerStreamForClient[v1alpha1.WatchTripResponse], error) {
	return c.watchTrip.CallServerStream(ctx, req)
}

// VerifyTrip calls ride.marketplace.v1alpha1.MarketplaceService.VerifyTrip.
func (c *marketplaceServiceClient) VerifyTrip(ctx context.Context, req *connect.Request[v1alpha1.VerifyTripRequest]) (*connect.Response[v1alpha1.VerifyTripResponse], error) {
	return c.verifyTrip.CallUnary(ctx, req)
}

// StartTrip calls ride.marketplace.v1alpha1.MarketplaceService.StartTrip.
func (c *marketplaceServiceClient) StartTrip(ctx context.Context, req *connect.Request[v1alpha1.StartTripRequest]) (*connect.Response[v1alpha1.StartTripResponse], error) {
	return c.startTrip.CallUnary(ctx, req)
}

// CancelTrip calls ride.marketplace.v1alpha1.MarketplaceService.CancelTrip.
func (c *marketplaceServiceClient) CancelTrip(ctx context.Context, req *connect.Request[v1alpha1.CancelTripRequest]) (*connect.Response[v1alpha1.CancelTripResponse], error) {
	return c.cancelTrip.CallUnary(ctx, req)
}

// EndTrip calls ride.marketplace.v1alpha1.MarketplaceService.EndTrip.
func (c *marketplaceServiceClient) EndTrip(ctx context.Context, req *connect.Request[v1alpha1.EndTripRequest]) (*connect.Response[v1alpha1.EndTripResponse], error) {
	return c.endTrip.CallUnary(ctx, req)
}

// MarketplaceServiceHandler is an implementation of the
// ride.marketplace.v1alpha1.MarketplaceService service.
type MarketplaceServiceHandler interface {
	GoOnline(context.Context, *connect.Request[v1alpha1.GoOnlineRequest]) (*connect.Response[v1alpha1.GoOnlineResponse], error)
	GoOffline(context.Context, *connect.Request[v1alpha1.GoOfflineRequest]) (*connect.Response[v1alpha1.GoOfflineResponse], error)
	GetStatus(context.Context, *connect.Request[v1alpha1.GetStatusRequest]) (*connect.Response[v1alpha1.GetStatusResponse], error)
	WatchStatus(context.Context, *connect.Request[v1alpha1.WatchStatusRequest], *connect.ServerStream[v1alpha1.WatchStatusResponse]) error
	GetLocation(context.Context, *connect.Request[v1alpha1.GetLocationRequest]) (*connect.Response[v1alpha1.GetLocationResponse], error)
	WatchLocation(context.Context, *connect.Request[v1alpha1.WatchLocationRequest], *connect.ServerStream[v1alpha1.WatchLocationResponse]) error
	UpdateLocation(context.Context, *connect.Request[v1alpha1.UpdateLocationRequest]) (*connect.Response[v1alpha1.UpdateLocationResponse], error)
	CreateTrip(context.Context, *connect.Request[v1alpha1.CreateTripRequest]) (*connect.Response[v1alpha1.CreateTripResponse], error)
	GetTrip(context.Context, *connect.Request[v1alpha1.GetTripRequest]) (*connect.Response[v1alpha1.GetTripResponse], error)
	WatchTrip(context.Context, *connect.Request[v1alpha1.WatchTripRequest], *connect.ServerStream[v1alpha1.WatchTripResponse]) error
	VerifyTrip(context.Context, *connect.Request[v1alpha1.VerifyTripRequest]) (*connect.Response[v1alpha1.VerifyTripResponse], error)
	StartTrip(context.Context, *connect.Request[v1alpha1.StartTripRequest]) (*connect.Response[v1alpha1.StartTripResponse], error)
	CancelTrip(context.Context, *connect.Request[v1alpha1.CancelTripRequest]) (*connect.Response[v1alpha1.CancelTripResponse], error)
	EndTrip(context.Context, *connect.Request[v1alpha1.EndTripRequest]) (*connect.Response[v1alpha1.EndTripResponse], error)
}

// NewMarketplaceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMarketplaceServiceHandler(svc MarketplaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	marketplaceServiceGoOnlineHandler := connect.NewUnaryHandler(
		MarketplaceServiceGoOnlineProcedure,
		svc.GoOnline,
		connect.WithSchema(marketplaceServiceGoOnlineMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGoOfflineHandler := connect.NewUnaryHandler(
		MarketplaceServiceGoOfflineProcedure,
		svc.GoOffline,
		connect.WithSchema(marketplaceServiceGoOfflineMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetStatusHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(marketplaceServiceGetStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceWatchStatusHandler := connect.NewServerStreamHandler(
		MarketplaceServiceWatchStatusProcedure,
		svc.WatchStatus,
		connect.WithSchema(marketplaceServiceWatchStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetLocationHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetLocationProcedure,
		svc.GetLocation,
		connect.WithSchema(marketplaceServiceGetLocationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceWatchLocationHandler := connect.NewServerStreamHandler(
		MarketplaceServiceWatchLocationProcedure,
		svc.WatchLocation,
		connect.WithSchema(marketplaceServiceWatchLocationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceUpdateLocationHandler := connect.NewUnaryHandler(
		MarketplaceServiceUpdateLocationProcedure,
		svc.UpdateLocation,
		connect.WithSchema(marketplaceServiceUpdateLocationMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceCreateTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceCreateTripProcedure,
		svc.CreateTrip,
		connect.WithSchema(marketplaceServiceCreateTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceGetTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceGetTripProcedure,
		svc.GetTrip,
		connect.WithSchema(marketplaceServiceGetTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceWatchTripHandler := connect.NewServerStreamHandler(
		MarketplaceServiceWatchTripProcedure,
		svc.WatchTrip,
		connect.WithSchema(marketplaceServiceWatchTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceVerifyTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceVerifyTripProcedure,
		svc.VerifyTrip,
		connect.WithSchema(marketplaceServiceVerifyTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceStartTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceStartTripProcedure,
		svc.StartTrip,
		connect.WithSchema(marketplaceServiceStartTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceCancelTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceCancelTripProcedure,
		svc.CancelTrip,
		connect.WithSchema(marketplaceServiceCancelTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	marketplaceServiceEndTripHandler := connect.NewUnaryHandler(
		MarketplaceServiceEndTripProcedure,
		svc.EndTrip,
		connect.WithSchema(marketplaceServiceEndTripMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/ride.marketplace.v1alpha1.MarketplaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MarketplaceServiceGoOnlineProcedure:
			marketplaceServiceGoOnlineHandler.ServeHTTP(w, r)
		case MarketplaceServiceGoOfflineProcedure:
			marketplaceServiceGoOfflineHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetStatusProcedure:
			marketplaceServiceGetStatusHandler.ServeHTTP(w, r)
		case MarketplaceServiceWatchStatusProcedure:
			marketplaceServiceWatchStatusHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetLocationProcedure:
			marketplaceServiceGetLocationHandler.ServeHTTP(w, r)
		case MarketplaceServiceWatchLocationProcedure:
			marketplaceServiceWatchLocationHandler.ServeHTTP(w, r)
		case MarketplaceServiceUpdateLocationProcedure:
			marketplaceServiceUpdateLocationHandler.ServeHTTP(w, r)
		case MarketplaceServiceCreateTripProcedure:
			marketplaceServiceCreateTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceGetTripProcedure:
			marketplaceServiceGetTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceWatchTripProcedure:
			marketplaceServiceWatchTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceVerifyTripProcedure:
			marketplaceServiceVerifyTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceStartTripProcedure:
			marketplaceServiceStartTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceCancelTripProcedure:
			marketplaceServiceCancelTripHandler.ServeHTTP(w, r)
		case MarketplaceServiceEndTripProcedure:
			marketplaceServiceEndTripHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMarketplaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMarketplaceServiceHandler struct{}

func (UnimplementedMarketplaceServiceHandler) GoOnline(context.Context, *connect.Request[v1alpha1.GoOnlineRequest]) (*connect.Response[v1alpha1.GoOnlineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.GoOnline is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GoOffline(context.Context, *connect.Request[v1alpha1.GoOfflineRequest]) (*connect.Response[v1alpha1.GoOfflineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.GoOffline is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetStatus(context.Context, *connect.Request[v1alpha1.GetStatusRequest]) (*connect.Response[v1alpha1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.GetStatus is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) WatchStatus(context.Context, *connect.Request[v1alpha1.WatchStatusRequest], *connect.ServerStream[v1alpha1.WatchStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.WatchStatus is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetLocation(context.Context, *connect.Request[v1alpha1.GetLocationRequest]) (*connect.Response[v1alpha1.GetLocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.GetLocation is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) WatchLocation(context.Context, *connect.Request[v1alpha1.WatchLocationRequest], *connect.ServerStream[v1alpha1.WatchLocationResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.WatchLocation is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) UpdateLocation(context.Context, *connect.Request[v1alpha1.UpdateLocationRequest]) (*connect.Response[v1alpha1.UpdateLocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.UpdateLocation is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) CreateTrip(context.Context, *connect.Request[v1alpha1.CreateTripRequest]) (*connect.Response[v1alpha1.CreateTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.CreateTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) GetTrip(context.Context, *connect.Request[v1alpha1.GetTripRequest]) (*connect.Response[v1alpha1.GetTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.GetTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) WatchTrip(context.Context, *connect.Request[v1alpha1.WatchTripRequest], *connect.ServerStream[v1alpha1.WatchTripResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.WatchTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) VerifyTrip(context.Context, *connect.Request[v1alpha1.VerifyTripRequest]) (*connect.Response[v1alpha1.VerifyTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.VerifyTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) StartTrip(context.Context, *connect.Request[v1alpha1.StartTripRequest]) (*connect.Response[v1alpha1.StartTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.StartTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) CancelTrip(context.Context, *connect.Request[v1alpha1.CancelTripRequest]) (*connect.Response[v1alpha1.CancelTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.CancelTrip is not implemented"))
}

func (UnimplementedMarketplaceServiceHandler) EndTrip(context.Context, *connect.Request[v1alpha1.EndTripRequest]) (*connect.Response[v1alpha1.EndTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ride.marketplace.v1alpha1.MarketplaceService.EndTrip is not implemented"))
}
