// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ride-app/marketplace-service/api/service"
	"github.com/ride-app/marketplace-service/config"
	"github.com/ride-app/marketplace-service/repositories/driver"
	"github.com/ride-app/marketplace-service/repositories/location"
	"github.com/ride-app/marketplace-service/repositories/status"
	"github.com/ride-app/marketplace-service/repositories/wallet"
	"github.com/ride-app/marketplace-service/third-party"
)

// Injectors from wire.go:

func InitializeService(config2 config.Config) (*service.MarketplaceServiceServer, error) {
	app, err := thirdparty.NewFirebaseApp(config2)
	if err != nil {
		return nil, err
	}
	firebaseImpl, err := statusrepository.NewFirebaseStatusRepository(app)
	if err != nil {
		return nil, err
	}
	locationrepositoryFirebaseImpl, err := locationrepository.NewFirebaseLocationRepository(app)
	if err != nil {
		return nil, err
	}
	impl, err := walletrepository.New(config2)
	if err != nil {
		return nil, err
	}
	driverrepositoryImpl, err := driverrepository.New(config2)
	if err != nil {
		return nil, err
	}
	marketplaceServiceServer := service.New(firebaseImpl, locationrepositoryFirebaseImpl, impl, driverrepositoryImpl)
	return marketplaceServiceServer, nil
}
